title: 건우의 포트폴리오 사이트
name: 박건우
email: parkkeonwo@naver.com
description: >-
  A.I developer


baseurl: ""
url: "https://parkgeonwoo2.github.io"


# profile 이미지
profile_image: images/pig.jpg


# SNS 아이디
facebook_id: #
instagram_id: #


# Youtube vid / youtube vid를 ""안에 넣으면됨
youtube_vid: #


# Custom Color
primary: ADD8E6 #b72cf0
primary_hover: B0C4DE #9a2dc7
color_1: ADD8E6 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2


# slider type 0  (텍스트가 우측 정렬된 슬라이더)
slider_0: # 형식에 맞추어 항목 추가
- background_url: images/geonwoo_bg3.jpg
  title: Park GeonWoo<br>Git Portfolio</br>


# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/geonwoo_bg1.jpg
  title: I am<br>AI Developer
  subtitle: >- 
    조금은 늦었지만<br>
    성장하고픈<br>
    초보 개발자 박건우입니다.


# About
about_meta: About Me
about_header: >- 
  "새로움에 두려움이 없는 학생"
about_introduce: >-
  "안녕하세요. 인공지능 전문가를 꿈꾸는 박건우입니다."
about_content: >-
  비전공자로서 21년 4월 부터 시작한 코딩에서 재미를 느껴 인공지능 개발자가 되고 싶은 학생입니다.<br>
  매일 배웠던 것을 onenote에 기록하고 최근에는 github, gitblog에 학습한 내용을 기록하고 있습니다. <br>
  아직 많이 부족하지만 열정 하나는 넘친다고 생각합니다. 감사합니다.

about_services: # 형식에 맞추어 항목 추가
- icon: icon-database
  name: deep-learning
- icon: icon-data
  name: big-data
- icon: icon-code
  name: Python
- icon: icon-code
  name: SQL

about_box_content: 안되면 될때까지 끝까지 책임지고 해결하자.
about_box_button:
  link: https://github.com/parkgeonwo
  name: 포기하지 말자!


# Tech  skill
tech_meta: TECH SKILLS
tech_header: 저는 현재 이것을 할 수 있습니다.
tech_content: 
tech_list: # 형식에 맞추어 항목 추가
- name: Python
  color: color-1
  animation: fadeInLeft
  percent: 50
  mark: 50
  content: 파이썬 기초, 데이터 분석과 시각화를 공부하고 파이썬 언어의 기본적인 문법에 대해 알고 있고, 자료구조 및 알고리즘을 파이썬으로 공부중입니다.
- name: 딥러닝
  color: color-2
  animation: fadeInRight
  percent: 30
  mark: 30
  content: 시작한지 얼마되지 않았지만 가장 관심이 많습니다. 딥러닝 책을 구매하여 기초적인 이론을 공부하고 프로젝트를 통해 모델을 만들어보고 있습니다.
- name: SQL
  color: color-3
  animation: fadeInLeft
  percent: 30
  mark: 30
  content: oracle을 통해 SQL을 처음 접해보고 MYSQL, MongoDB등 SQL 기본적인 문법을 알고 있습니다. SQLD 자격증을 취득하였고, 향후 SQLP 자격증에 도전할것입니다.
- name: Github
  color: color-4
  animation: fadeInRight
  percent: 30
  mark: 30
  content: github서버를 활용하여 블로그 및 포트폴리오 사이트를 관리하고 있고, 코드를 적으면 최대한 github에 commit하려고 노력중입니다.
tech_desc: 여러가지 딥러닝 개발을 통해 다양한 프로젝트를 진행할 예정입니다.<br>또한, 딥러닝 관련 논문을 공부하여 구현해보고, computer science 학습을 진행할 예정입니다. 


# Project
project_meta: My Work
project_header: PROJECT
project_introduce: <span>개인 프로젝트 / </span><span>팀 프로젝트</span>
project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)    # 더보기 내용
project_load_more_url: https://github.com/parkgeonwo


project_my_name: 개인프로젝트
project_my: # 형식에 맞추어 항목 추가

- background_url: images/geonwoo_squid.PNG
  animation: fadeInLeft
  name: AI-Face-detect-squid-game
  description: (2021.11) AI로 내 얼굴을 분석하여 드라마 오징어게임에서 어떤 출연자와 비슷한지 알려주는 서비스 개발
  detail_url: https://github.com/parkgeonwo/AI-Face-detect-squid-game
  readmore_url: https://parkgeonwo.github.io/AI-Face-detect-squid-game/

- background_url: images/geonwoo_lol.PNG
  animation: fadeInLeft
  name: lol-game-data-analysis
  description: (2021.09) 리그오브레전드 승리에 미치는 조건 분석
  detail_url: https://github.com/parkgeonwo/lol-game-data-analysis
  readmore_url: https://github.com/parkgeonwo/lol-game-data-analysis

project_team_name: 팀프로젝트
project_team: # 형식에 맞추어 항목 추가

- background_url: images/geonwoo_bg1.jpg
  animation: fadeInRight
  name: street-side-walk-object-detection
  description: (2021.10) yolo v4, v5를 활용한 도보 위 객체 탐지 모델 개발
  detail_url: https://github.com/parkgeonwo/yolov4-v5-street-side-walk-object-detection
  readmore_url: https://github.com/parkgeonwo/yolov4-v5-street-side-walk-object-detection





# Experience
exp_meta: What have I achieved?
exp_header: 저는 이런 "경험"들을 해봤습니다.
exp_content: 현재 개발로서는 큰 도움은 되지 않을 수 있지만, 회사에서 필요로 한다면 이런 역량도 가지고 있습니다.
exp_services: # 형식에 맞추어 항목 추가
- name: 매니지먼트
  color: color-1
  icon: icon-bulb
  content: 학과 부학생회장을 맡아 학부생들의 문제를 해결하고 많은 행사들을 기획하고 추진하였습니다.
- name: 기술습득
  color: color-2
  icon: icon-home
  content: 제가 선택한 길, 항상 열정을 다해 공부하며 새로운 기술에 대해 즐거운 마음으로 배웁니다.
- name: 책임감,도전
  color: color-3
  icon: icon-phone3
  content: 새로운 프로젝트에 계속 도전하려하고 책임지고 내 몫은 다한다는 생각을 가지고 있습니다.

exp_counters:
- name: project
  count: 4
  speed: 4000


# Career
carerr_meta: career
career_header: Work Career
career_list:
- name: 빅데이터/머신러닝 전문가 양성과정
  date: 2020.04~2020.10
  content: SQL, 파이썬, R, 리눅스&하둡 언어에 대한 기초적인 문법부터 알고리즘 학습을 통한 프로그래밍 개발능력 교육, 머신러닝, 딥러닝 개발
  color: color-1
  icon: icon-pen2
  animation: fadeInLeft



# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: Big data/Machine learning education
  subtitle: 빅데이터/머신러닝 전문가 양성과정
  date: 2020.04 - 2020.10
  content: 
- title: HONGIK UNIVERSITY
  subtitle: 홍익대학교 신소재 공학과 졸업
  date: 2014.03 - 2020.08
  content:  
- title: yeungnam HIGH SCHOOL
  subtitle: 영남고등학교
  date: 2010.03 - 2013.02
  content: >-



# Blog
blog_meta: self-improvement
blog_header: BLOG
blog_load_more: 더 발전하기 위해 항상 노력합니다    # 더보기 내용
blog_load_more_url: https://parkgeonwo.github.io
blog_list:

- title: 코딩 노트
  subtitle: 코딩을 처음 접한 시점부터 지금까지 코딩 노트
  date: 2021.04
  content: 
  thumbnail_url: images/geonwoo_onenote.PNG
  link: "https://onedrive.live.com/redir?resid=F684E59F71FF596D%217027&page=View&wd=target%28SQL.one%7C76e7d2fd-08ba-4191-a981-553ab2dd8351%2FSQL%20%EC%88%98%EC%97%85%20%EB%AA%A9%EC%B0%A8%7C2b95ef33-cf33-4352-b0d6-7007d0c5cec0%2F%29"

- title: 개발 노트 블로그
  subtitle: 개발 블로그 운영
  date: 2022.01
  content: 
  thumbnail_url: images/geonwoo_blog.PNG
  link: "https://parkgeonwo.github.io"



# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: parkkeonwo@naver.com
  icon: icon-globe-outline
- title: 서울특별시
  icon: icon-map
- title: +82 10 xxxx xxxx
  icon: icon-phone
- title: github
  icon: icon-layers2
  url: https://github.com/parkgeonwo
contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다. :)


optional_front_matter:
  remove_originals:    true
